uploads = []
generated = []

[[outputs]]
id = "XHHvFLh_tTXfR1Nem4KPD"
uri = "file://Perjalanan_Hidup_v1.mp3"
type = "audio"
title = "Perjalanan Hidup - Versi 1 (AI Generated)"

[[outputs]]
id = "VpwnSP7EemMjedo1fqQ-7"
uri = "file://Janji_Selamanya_v1.mp3"
type = "audio"
title = "Janji Selamanya | 21 Mei 2026 | Indonesian Slow Rock Ballad — Versi 1 (6:30)"

[[outputs]]
id = "uWp9dk9U1x2IFne39iKEK"
uri = "file://Janji_Selamanya_v2.mp3"
type = "audio"
title = "Janji Selamanya | 21 Mei 2026 | Indonesian Slow Rock Ballad — Versi 2 (4:28)"
