uploads = []
generated = []

[[outputs]]
id = "XHHvFLh_tTXfR1Nem4KPD"
uri = "file://Perjalanan_Hidup_v1.mp3"
type = "audio"
title = "Perjalanan Hidup - Versi 1 (AI Generated)"

[[outputs]]
id = "VpwnSP7EemMjedo1fqQ-7"
uri = "file://Janji_Selamanya_v1.mp3"
type = "audio"
title = "Janji Selamanya | 21 Mei 2026 | Indonesian Slow Rock Ballad — Versi 1 (6:30)"

[[outputs]]
id = "uWp9dk9U1x2IFne39iKEK"
uri = "file://Janji_Selamanya_v2.mp3"
type = "audio"
title = "Janji Selamanya | 21 Mei 2026 | Indonesian Slow Rock Ballad — Versi 2 (4:28)"

[[outputs]]
id = "Z4jnlE9vjopm0KWaLqTKw"
uri = "file://Hujan_Malam_v1.mp3"
type = "audio"
title = "Hujan Malam | 21 Mei 2026 | Sad Pop, Melancholic Rain Vibes — Versi 1 (5:23)"

[[outputs]]
id = "fYOAtV5XY413QgtQbsvQE"
uri = "file://Hujan_Malam_v2.mp3"
type = "audio"
title = "Hujan Malam | 21 Mei 2026 | Sad Pop, Melancholic Rain Vibes — Versi 2 (4:24)"

[[outputs]]
id = "DGJ0lDqrKqMvtjuN_DNbX"
uri = "file://Kienai_Namida_v1.mp3"
type = "audio"
title = "消えない涙 (Kienai Namida) | 21 Mei 2026 | Japanese Sad Ballad, Anime OST — Versi 1 (5:10)"

[[outputs]]
id = "VxaYsl80o09Mw1M1DLYnn"
uri = "file://Kienai_Namida_v2.mp3"
type = "audio"
title = "消えない涙 (Kienai Namida) | 21 Mei 2026 | Japanese Sad Ballad, Anime OST — Versi 2 (5:49)"
